.TH MERGEN 1 "December 2025" "v0.9.5" "User Commands"
.SH NAME
mergen \- Modern Download Manager
.SH SYNOPSIS
.B mergen
[URL]
.SH DESCRIPTION
Mergen is a modern, high-performance download manager with support for:
.IP \[bu] 2
Multi-threaded downloads
.IP \[bu]
Video streaming support (HLS/DASH)
.IP \[bu]
Browser integration (Chrome/Firefox)
.IP \[bu]
Queue management
.SH OPTIONS
.TP
.B URL
Optional URL to start downloading immediately.
.SH FILES
.TP
.B ~/.config/mergen/
Configuration directory.
.SH AUTHOR
Tunahan Yardimci
.SH SEE ALSO
https://github.com/Tunahanyrd/mergen
